import {Hero} from './hero'

export const HEROES: Hero[] = [
    { name: 'Ian Gallant', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'Pyromancy||Body Enhancing Magic' 
},
    { name: 'Maoh Gallant|Hellcicer', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'N/A' 
},
    { name: 'Anii Gallant', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'tba' 
},
    { name: 'Isa Gallant', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test' , 
    magicTypes:'tba'
},
    { name: 'Ira Gallant', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'tba' 
},
    { name: 'Baccarat', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test' , 
    magicTypes:'Hydromancy, Aeromancy, Psychic Magic'
},
    { name: 'Mokuteki Delinq', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test' , 
    magicTypes:'Body Enhancing Magic'
},
    { name: 'Aibo', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'?' 
},
    { name: 'Helia Regimez', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'Aeromancy, Body Enhancing Magic' 
},
    { name: 'Osen', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'tba' 
},
    { name: 'Kasamori', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test' , 
    magicTypes:'tba'
},
    { name: 'Dragheart Hellhuntre', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'N/A' 
},
    { name: 'Camus Rieux', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'tba' 
},
    { name: 'Liebe Helllife', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test' , 
    magicTypes:'N/A'
},
    { name: 'Dragostei Helllife', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test' , 
    magicTypes:'N/A'},
    { name: 'Calibur Hellcicer', 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'N/A' 
},
    { name: `Aaron D'sa `, 
    traits: 'Test', 
    Abilities: 'Test', 
    Backstory:'Test', 
    magicTypes:'tba' 
},
]