import { Hero } from './hero';

export const HEROES_WIP: Hero[] = [
  {
    name: 'Sand Planet Queen',
    traits:
      'Full on kuudere, actually a really nice and caring person, laughs rarely but if she does then with all her heart',
    Abilities:
      'Walking without ever stopping, sleeping while walking and navigating, transforming sand into water, solidifying sand to walk more easily and not anger the sandworms living under the entire desert',
    Backstory: `Has been wandering the great 'Desert Planet' for all her life to her knowledge, picks up anyone unfortunate to get lost in the sandy plains, earned her the title of Sand Planet Queen `,
    magicTypes: 'Transformation Magic, Terramancy, Aeromancy, Hydromancy',
    SongInspired: 'Vocaloid - Suna No Wakusei',
    Faceclaim: '',
  },
  {
    name: 'Zombie Girl',
    traits: 'tba',
    Abilities: 'tba',
    Backstory:
      'Killed and afterwards revived as a supposed servant zombie of the Soulmancer, however becomes self-concious at some point and starts to fight against him, fed up as a zombie,',
    magicTypes: 'tba',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Alchemist',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'tba',
    SongInspired: 'Philmont - The Alchemist',
    Faceclaim: '',
  },
  {
    name: 'Soulmancer',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'Soulmancy, Psychologic Magic',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Queen of Kings',
    traits: `Strong Misunderstanding of the word 'love', constantly remarries and assigns new people to being the new king of her kingdom. `,
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'Illusion Magic, Restoring Magic, Pyromancy',
    SongInspired: 'Vocaloid - King',
    Faceclaim: '',
  },
  {
    name: 'Succubus Devil',
    traits: 'tba',
    Abilities: 'tba',
    Backstory:
      'Old friend of Maoh, maybe? Who in the meantime became a devil herself?',
    magicTypes: 'tba',
    SongInspired: 'Vocaloid - Sweet Devil',
    Faceclaim: '',
  },
  {
    name: 'Dreamdemon',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'tba',
    SongInspired: 'Vocaloid - Monochrome Dream Eating Baku ',
    Faceclaim: '',
  },
  {
    name: 'Mephisto Kucabara',
    traits: 'Lawyer of hell',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'tba',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Archdemon Devil',
    traits: 'tba',
    Abilities: 'Blue flames',
    Backstory: 'Tba',
    magicTypes: 'tba',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Demon Devil',
    traits: 'tba',
    Abilities: 'Blue flames',
    Backstory: 'tba',
    magicTypes: 'tba',
    SongInspired: 'No',
    Faceclaim: '',
  },
];
