import { Hero } from '../models/hero';

export const HEROES_WIP: Hero[] = [
  {
    name: 'Sand Planet Queen',
    traits:
      'Full on kuudere, actually a really nice and caring person, laughs rarely but if she does then with all her heart',
    Abilities:
      'Walking without ever stopping, sleeping while walking and navigating, transforming sand particles into water, solidifying sand to walk more easily and not anger the sandworms living under the entire desert',
    Backstory: `Has been wandering the great 'Desert Planet' for all her life to her knowledge, picks up anyone unfortunate to get lost in the sandy plains, earned her the title of Sand Planet Queen `,
    magicTypes: 'Transformation Magic, Terramancy, Aeromancy, Hydromancy',
    SongInspired: 'Vocaloid - Suna No Wakusei',
    Faceclaim: 'https://static.zerochan.net/Suna.no.Wakusei.full.2121399.png',
  },
  {
    name: 'Zombie Girl',
    traits: 'tba',
    Abilities: 'tba',
    Backstory:
      'Killed and afterwards revived as a supposed servant zombie of the Soulmancer, however becomes self-concious at some point and starts to fight against him, fed up as a zombie,',
    magicTypes: 'tba',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Alchemist',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'tba',
    SongInspired: 'Philmont - The Alchemist',
    Faceclaim: '',
  },
  {
    name: 'Soulmancer',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'Soulmancy, Psychologic Magic',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Queen of Kings',
    traits: `Strong Misunderstanding of the word 'love', constantly remarries and assigns new people to being the new king of her kingdom. `,
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'Illusion Magic, Restoring Magic, Pyromancy',
    SongInspired: 'Vocaloid - King',
    Faceclaim: '',
  },
  {
    name: 'Succubus Devil',
    traits:
      'a particular liking to couches and enjoys laying on them, refuses all sorts of stools',
    Abilities: 'tba',
    Backstory:
      'A succubus Maoh tended to spend a lot of time with back in the days',
    magicTypes: 'N/A',
    SongInspired: 'Vocaloid - Sweet Devil',
    Faceclaim:
      'https://2.bp.blogspot.com/-HXoYdtZ37YI/ViHXt7jpXKI/AAAAAAAAAO0/Lv5R6TDesfg/s400/Nonon%2Bon%2Bcouch.jpg',
  },
  {
    name: 'Dreamdemon',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'N/A',
    SongInspired: 'Vocaloid - Monochrome Dream Eating Baku ',
    Faceclaim: '',
  },
  {
    name: 'Mephisto Kucabara',
    traits: 'Lawyer of hell',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'N/A',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Archdemon Devil',
    traits: 'tba',
    Abilities: 'Blue flames',
    Backstory: 'Tba',
    magicTypes: 'N/A',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Demon Devil',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'N/A',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Monster/Werewolf?',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'Someone who played and experimented too much with transformation magic, not able to really think or talk anymore, despaired into nothingness due to him being hated as a proclaimed monster, accidentally wanders into the labaratory of the mad scientist girl where he gets tended to and actually for once feels at least kind of accepted, only as test subject at the start however, ',
    magicTypes: 'N/A',
    SongInspired: 'Mili - RTRT',
    Faceclaim: '',
  },
  {
    name: 'Mad Scientist',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: `Mad Scientist who picks up the Monster and tames him as hers, teaches the monster more and more, eventually growing fond of it and even fully falling in love with it, her life always was too easy in the way of problems she dealt with, the monster finally offering some retort and issues towards her, `,
    magicTypes: 'N/A',
    SongInspired: 'Mili - RTRT',
    Faceclaim: '',
  },
  {
    name: 'Demon Idol and P TSN',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'Idol of TSN',
    magicTypes: 'tba',
    SongInspired: 'TopHamHatKyo - Princess / Mister Jewel Box',
    Faceclaim: 'https://i.kfs.io/album/global/82205995,0v1/fit/500x500.jpg',
  },
  {
    name: 'Geometry Time',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: '',
    magicTypes: 'tba',
    SongInspired:
      'Proof Geometric Construction Can Solve All Love Affairs - Vocaloid',
    Faceclaim: '',
  },
  {
    name: 'Robot?|Android?',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'tba',
    magicTypes: 'N/A',
    SongInspired: 'Mili - world.execute(me)',
    Faceclaim: '',
  },
  {
    name: 'in the company of worms',
    traits: `Seemingly friendly and caring, however rotten and jealous of other people instead, killing those who aren't happy with their life despite not a being that bad, maybe even tries beforehand to help them out of their issues`,
    Abilities: 'tba',
    Backstory: '',
    magicTypes: 'N/A',
    SongInspired: 'yes',
    Faceclaim: '',
  },
  {
    name: 'Mamoru Mugabunai',
    traits:
      '守 (protect, guard but also obey, observe) る (exile) 無 (nothingness, none, nothing, nil, not) 我 (ego, selfish, I, oneself) 危 (danger, risky, critical)]  -->Mamoru Mugabunai= spoken name',
    Abilities: 'tba',
    Backstory:
      'Guy with the aberration of a dolphin which has him see all the many people affected by an aberration. This comes from his high will to help, helping people so much that his own life is putting on risk at any time. Deep inside believes nobody loves him --> got rejected multiple times. Later on learns from Genhito or how to take care of aberrations with the constant risk of dying however due to dangerous aberrations, badly in love with Mihitsu  ',
    magicTypes: 'N/A',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Mihitsu Aimoto ',
    traits: `身 (	somebody, person, one's station in life ) 日 ( day, sun, Japan, !!counter for days!! ) 佚 ( !!lost!!, !!hide!!, peace, !!mistake!!, beautiful, in turn )-->Mihiitsu --> shortened Mihitsu 未必 = not sure, 愛 (Love,Reference, Affection --> also readable as 相 which means together, aspect, mutual) 本(Source,origin,root)`,
    Abilities: 'tba',
    Backstory:
      'Classmate of Mamoru, in her deepest feelings in love with him, pushes it off to the side and ignores it however to go for more handsome/interesting guys, causes her to attract an aberration --> Mamoru picks up on it and brings her to Genhito who tells her exactly how things are and how she could bring both of them out of their aberration by confessing. ',
    magicTypes: 'N/A',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'Genhito Kaimono',
    traits: '玄  (mysterious ) 人 ( person ) 開 ( To Open, Unfold, Unseal ) 者 ( Person, Someone ) ',
    Abilities: 'tba',
    Backstory: `Oshino kind of role, expert for Aberrations, starts by helping out Mamoru after he has been involved with a dangerous Aberration, gives Mamoru an amulet to wear to completely nullify his aberration for the time he wears it(he barely wears it as he chooses to protect people from aberrations), despises Mihiitsu as she is childish and egoistic in his eyes('I absolutely despise you, down to the core,really.')`,
    magicTypes: 'N/A',
    SongInspired: 'No',
    Faceclaim: '',
  },
  {
    name: 'MonogatariVerseMLI',
    traits: 'tba',
    Abilities: 'tba',
    Backstory: 'A lot of WIP love interest characters to spice things up.',
    magicTypes: 'N/A',
    SongInspired: 'No',
    Faceclaim: '',
  },
];
